#!/bin/bash

# Comprehensive color refactoring script v2
# This script replaces ALL remaining hardcoded Tailwind color classes

echo "Starting comprehensive color refactoring v2..."

# Find all TSX and TS files
FILES=$(find src -type f \( -name "*.tsx" -o -name "*.ts" \) ! -path "*/node_modules/*")

for file in $FILES; do
  # Replace all bg-orange-* variants
  sed -i '' 's/bg-orange-50/bg-primary/g' "$file"
  sed -i '' 's/bg-orange-100/bg-primary/g' "$file"
  sed -i '' 's/bg-orange-200/bg-primary/g' "$file"
  sed -i '' 's/bg-orange-300/bg-primary/g' "$file"
  sed -i '' 's/bg-orange-400/bg-primary/g' "$file"
  sed -i '' 's/bg-orange-500/bg-primary/g' "$file"
  sed -i '' 's/bg-orange-600/bg-primary/g' "$file"
  sed -i '' 's/bg-orange-700/bg-primary/g' "$file"
  sed -i '' 's/bg-orange-800/bg-primary/g' "$file"
  sed -i '' 's/bg-orange-900/bg-primary/g' "$file"
  
  # Replace all bg-green-* variants
  sed -i '' 's/bg-green-50/bg-primary/g' "$file"
  sed -i '' 's/bg-green-100/bg-primary/g' "$file"
  sed -i '' 's/bg-green-200/bg-primary/g' "$file"
  sed -i '' 's/bg-green-300/bg-primary/g' "$file"
  sed -i '' 's/bg-green-400/bg-primary/g' "$file"
  sed -i '' 's/bg-green-500/bg-primary/g' "$file"
  sed -i '' 's/bg-green-600/bg-primary/g' "$file"
  sed -i '' 's/bg-green-700/bg-primary/g' "$file"
  sed -i '' 's/bg-green-800/bg-primary/g' "$file"
  sed -i '' 's/bg-green-900/bg-primary/g' "$file"
  
  # Replace all bg-blue-* variants
  sed -i '' 's/bg-blue-50/bg-secondary/g' "$file"
  sed -i '' 's/bg-blue-100/bg-secondary/g' "$file"
  sed -i '' 's/bg-blue-200/bg-secondary/g' "$file"
  sed -i '' 's/bg-blue-300/bg-secondary/g' "$file"
  sed -i '' 's/bg-blue-400/bg-secondary/g' "$file"
  sed -i '' 's/bg-blue-500/bg-secondary/g' "$file"
  sed -i '' 's/bg-blue-600/bg-secondary/g' "$file"
  sed -i '' 's/bg-blue-700/bg-secondary/g' "$file"
  sed -i '' 's/bg-blue-800/bg-secondary/g' "$file"
  sed -i '' 's/bg-blue-900/bg-secondary/g' "$file"
  
  # Replace all bg-purple-* variants
  sed -i '' 's/bg-purple-50/bg-secondary/g' "$file"
  sed -i '' 's/bg-purple-100/bg-secondary/g' "$file"
  sed -i '' 's/bg-purple-200/bg-secondary/g' "$file"
  sed -i '' 's/bg-purple-300/bg-secondary/g' "$file"
  sed -i '' 's/bg-purple-400/bg-secondary/g' "$file"
  sed -i '' 's/bg-purple-500/bg-secondary/g' "$file"
  sed -i '' 's/bg-purple-600/bg-secondary/g' "$file"
  sed -i '' 's/bg-purple-700/bg-secondary/g' "$file"
  sed -i '' 's/bg-purple-800/bg-secondary/g' "$file"
  sed -i '' 's/bg-purple-900/bg-secondary/g' "$file"
  
  # Replace all bg-indigo-* variants
  sed -i '' 's/bg-indigo-50/bg-secondary/g' "$file"
  sed -i '' 's/bg-indigo-100/bg-secondary/g' "$file"
  sed -i '' 's/bg-indigo-200/bg-secondary/g' "$file"
  sed -i '' 's/bg-indigo-300/bg-secondary/g' "$file"
  sed -i '' 's/bg-indigo-400/bg-secondary/g' "$file"
  sed -i '' 's/bg-indigo-500/bg-secondary/g' "$file"
  sed -i '' 's/bg-indigo-600/bg-secondary/g' "$file"
  sed -i '' 's/bg-indigo-700/bg-secondary/g' "$file"
  sed -i '' 's/bg-indigo-800/bg-secondary/g' "$file"
  sed -i '' 's/bg-indigo-900/bg-secondary/g' "$file"
  
  # Replace all bg-pink-* variants
  sed -i '' 's/bg-pink-50/bg-secondary/g' "$file"
  sed -i '' 's/bg-pink-100/bg-secondary/g' "$file"
  sed -i '' 's/bg-pink-200/bg-secondary/g' "$file"
  sed -i '' 's/bg-pink-300/bg-secondary/g' "$file"
  sed -i '' 's/bg-pink-400/bg-secondary/g' "$file"
  sed -i '' 's/bg-pink-500/bg-secondary/g' "$file"
  sed -i '' 's/bg-pink-600/bg-secondary/g' "$file"
  sed -i '' 's/bg-pink-700/bg-secondary/g' "$file"
  sed -i '' 's/bg-pink-800/bg-secondary/g' "$file"
  sed -i '' 's/bg-pink-900/bg-secondary/g' "$file"
  
  # Replace all from-* gradient variants
  sed -i '' 's/from-orange-50/from-primary/g' "$file"
  sed -i '' 's/from-orange-100/from-primary/g' "$file"
  sed -i '' 's/from-orange-200/from-primary/g' "$file"
  sed -i '' 's/from-orange-300/from-primary/g' "$file"
  sed -i '' 's/from-orange-400/from-primary/g' "$file"
  sed -i '' 's/from-orange-500/from-primary/g' "$file"
  sed -i '' 's/from-orange-600/from-primary/g' "$file"
  sed -i '' 's/from-orange-700/from-primary/g' "$file"
  sed -i '' 's/from-orange-800/from-primary/g' "$file"
  sed -i '' 's/from-orange-900/from-primary/g' "$file"
  
  sed -i '' 's/from-green-50/from-primary/g' "$file"
  sed -i '' 's/from-green-100/from-primary/g' "$file"
  sed -i '' 's/from-green-200/from-primary/g' "$file"
  sed -i '' 's/from-green-300/from-primary/g' "$file"
  sed -i '' 's/from-green-400/from-primary/g' "$file"
  sed -i '' 's/from-green-500/from-primary/g' "$file"
  sed -i '' 's/from-green-600/from-primary/g' "$file"
  sed -i '' 's/from-green-700/from-primary/g' "$file"
  sed -i '' 's/from-green-800/from-primary/g' "$file"
  sed -i '' 's/from-green-900/from-primary/g' "$file"
  
  sed -i '' 's/from-blue-50/from-secondary/g' "$file"
  sed -i '' 's/from-blue-100/from-secondary/g' "$file"
  sed -i '' 's/from-blue-200/from-secondary/g' "$file"
  sed -i '' 's/from-blue-300/from-secondary/g' "$file"
  sed -i '' 's/from-blue-400/from-secondary/g' "$file"
  sed -i '' 's/from-blue-500/from-secondary/g' "$file"
  sed -i '' 's/from-blue-600/from-secondary/g' "$file"
  sed -i '' 's/from-blue-700/from-secondary/g' "$file"
  sed -i '' 's/from-blue-800/from-secondary/g' "$file"
  sed -i '' 's/from-blue-900/from-secondary/g' "$file"
  
  sed -i '' 's/from-purple-50/from-secondary/g' "$file"
  sed -i '' 's/from-purple-100/from-secondary/g' "$file"
  sed -i '' 's/from-purple-200/from-secondary/g' "$file"
  sed -i '' 's/from-purple-300/from-secondary/g' "$file"
  sed -i '' 's/from-purple-400/from-secondary/g' "$file"
  sed -i '' 's/from-purple-500/from-secondary/g' "$file"
  sed -i '' 's/from-purple-600/from-secondary/g' "$file"
  sed -i '' 's/from-purple-700/from-secondary/g' "$file"
  sed -i '' 's/from-purple-800/from-secondary/g' "$file"
  sed -i '' 's/from-purple-900/from-secondary/g' "$file"
  
  sed -i '' 's/from-indigo-50/from-secondary/g' "$file"
  sed -i '' 's/from-indigo-100/from-secondary/g' "$file"
  sed -i '' 's/from-indigo-200/from-secondary/g' "$file"
  sed -i '' 's/from-indigo-300/from-secondary/g' "$file"
  sed -i '' 's/from-indigo-400/from-secondary/g' "$file"
  sed -i '' 's/from-indigo-500/from-secondary/g' "$file"
  sed -i '' 's/from-indigo-600/from-secondary/g' "$file"
  sed -i '' 's/from-indigo-700/from-secondary/g' "$file"
  sed -i '' 's/from-indigo-800/from-secondary/g' "$file"
  sed -i '' 's/from-indigo-900/from-secondary/g' "$file"
  
  sed -i '' 's/from-pink-50/from-secondary/g' "$file"
  sed -i '' 's/from-pink-100/from-secondary/g' "$file"
  sed -i '' 's/from-pink-200/from-secondary/g' "$file"
  sed -i '' 's/from-pink-300/from-secondary/g' "$file"
  sed -i '' 's/from-pink-400/from-secondary/g' "$file"
  sed -i '' 's/from-pink-500/from-secondary/g' "$file"
  sed -i '' 's/from-pink-600/from-secondary/g' "$file"
  sed -i '' 's/from-pink-700/from-secondary/g' "$file"
  sed -i '' 's/from-pink-800/from-secondary/g' "$file"
  sed -i '' 's/from-pink-900/from-secondary/g' "$file"
  
  # Replace all to-* gradient variants (similar pattern for to- and via-)
  sed -i '' 's/to-orange-500/to-primary/g' "$file"
  sed -i '' 's/to-orange-600/to-primary/g' "$file"
  sed -i '' 's/to-green-500/to-primary/g' "$file"
  sed -i '' 's/to-green-600/to-primary/g' "$file"
  sed -i '' 's/to-blue-500/to-secondary/g' "$file"
  sed -i '' 's/to-blue-600/to-secondary/g' "$file"
  sed -i '' 's/to-blue-700/to-secondary/g' "$file"
  sed -i '' 's/to-purple-500/to-secondary/g' "$file"
  sed -i '' 's/to-purple-600/to-secondary/g' "$file"
  sed -i '' 's/to-purple-700/to-secondary/g' "$file"
  sed -i '' 's/to-indigo-500/to-secondary/g' "$file"
  sed -i '' 's/to-indigo-600/to-secondary/g' "$file"
  sed -i '' 's/to-indigo-700/to-secondary/g' "$file"
  sed -i '' 's/to-pink-500/to-secondary/g' "$file"
  sed -i '' 's/to-pink-600/to-secondary/g' "$file"
  sed -i '' 's/to-pink-700/to-secondary/g' "$file"
  
  # Replace hover states
  sed -i '' 's/hover:from-orange-700/hover:from-primary/g' "$file"
  sed -i '' 's/hover:from-blue-700/hover:from-secondary/g' "$file"
  sed -i '' 's/hover:from-purple-700/hover:from-secondary/g' "$file"
  sed -i '' 's/hover:to-indigo-700/hover:to-secondary/g' "$file"
  sed -i '' 's/hover:to-purple-700/hover:to-secondary/g' "$file"
  sed -i '' 's/hover:to-pink-700/hover:to-secondary/g' "$file"
done

echo "Comprehensive color refactoring v2 complete!"
echo "Files processed: $(echo "$FILES" | wc -l)"
